mysql:
  container_name: mysql
  build: mysql/.
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=petclinic
    - MYSQL_USER=petclinic
    - MYSQL_PASSWORD=petclinic
spring:
  container_name: spring
  build: spring/.
  links:
    - "mysql:dbhost"
  ports:
    - "80:8080"