version: '2'
services:
  mysql:
    container_name: mysql
    build: mysql/.
    image: petclinic_mysql:1.4.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=petclinic
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
  spring:
    container_name: spring
    build: spring/.
    image: petclinic_spring:1.4.2
    links:
      - "mysql:dbhost"
    ports:
      - "80:8080"