mysql:
  image: mysql
  container_name: mysql
  ports:
    - "3306:3306"
  environment:
    - MYSQL_ROOT_PASSWORD=secret
    - MYSQL_DATABASE=petclinic
    - MYSQL_USER=petclinic
    - MYSQL_PASSWORD=petclinic
petclinic:
  image: spring-petclinic:1.4.2
  container_name: petclinic
  links:
    - "mysql:dbhost"
  ports:
    - "80:8080"